baseURL = 'auntjoestar.github.io/dnd_characters_portfoil/'
languageCode = 'es-ni'
title = "Crista's D&D Characters"
theme = "dnd_characters"
defaultContentLanguage = "es"
canonicalURL = "https://auntjoestar.github.io/dnd_characters_portfoil/"
keywords = ["DnD", "Dungeons", "Dragons", "Calabozos", "Mazmorras", "Tiefling", "Sorcerer", "Characters", "Personajes", "Portfoil", "Portafolios"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Personajes"
    pre = "personajes"
    url = "/personajes/"
    weight = 2

[params]
favicon = "img/favicon.ico" # Path to favicon file

[permalinks]
posts = "/personajes/:slug/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

