baseURL = 'http://example.org/'
languageCode = 'es-ni'
title = "Crista's D&D Characters"
theme = "dnd_characters"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Personajes"
    pre = "personajes"
    url = "/personajes/"
    weight = 2

[params]
favicon = "/img/favicon.ico" # Path to favicon file

[permalinks]
posts = "/personajes/:slug/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
